#!/bin/sh

# PROVIDE: VibbeCoin
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# VibbeCoin_enable (bool): Set to NO by default. Set this variable to YES if you want to enable VibbeCoin service.
# VibbeCoin_config (path): Set to /usr/local/etc/VibbeCoin.conf by default.
# VibbeCoin_user:  The user account VibbeCoin daemon runs as. It uses 'root' user by default.
# VibbeCoin_group: The group account VibbeCoin daemon runs as. It uses 'wheel' group by default.
# VibbeCoin_datadir (str): Default to "/var/db/VibbeCoin". Base data directory.

. /etc/rc.subr

name=VibbeCoin
rcvar=VibbeCoin_enable

: ${VibbeCoin_enable:=NO}
: ${VibbeCoin_config=/usr/local/etc/VibbeCoin.conf}
: ${VibbeCoin_datadir=/var/db/VibbeCoin}
: ${VibbeCoin_user="root"}
: ${VibbeCoin_group="wheel"}

required_files=${VibbeCoin_config}
command=/usr/local/bin/VibbeCoind
VibbeCoin_chdir=${VibbeCoin_datadir}
pidfile="${VibbeCoin_datadir}/VibbeCoind.pid"
stop_cmd=VibbeCoin_stop
command_args="-conf=${VibbeCoin_config} -datadir=${VibbeCoin_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

VibbeCoin_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${VibbeCoin_datadir}
	[ $? -eq 0 ] && chown -R ${VibbeCoin_user}:${VibbeCoin_group} ${VibbeCoin_datadir}
}

VibbeCoin_prestart()
{
	if [ ! -d "${VibbeCoin_datadir}/." ]; then
		VibbeCoin_create_datadir || return 1
	fi
}

VibbeCoin_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

VibbeCoin_stop()
{
    VibbeCoin_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${VibbeCoin_config} -datadir=${VibbeCoin_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
